# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alnfile', models.FileField(upload_to=projects.models.alignment_file_name)),
                ('name', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlignmentHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qseqid', models.TextField()),
                ('sseqid', models.TextField()),
                ('pident', models.TextField()),
                ('length', models.TextField()),
                ('mismatch', models.TextField()),
                ('gapopen', models.TextField()),
                ('qstart', models.TextField()),
                ('qend', models.TextField()),
                ('sstart', models.TextField()),
                ('send', models.TextField()),
                ('evalue', models.TextField()),
                ('bitscore', models.TextField()),
                ('GI', models.TextField()),
                ('GeneID', models.TextField()),
                ('NCBI_taxon_of_the_reference', models.TextField()),
                ('Lowest_taxon_of_the_cluster', models.TextField()),
                ('RepID', models.TextField()),
                ('Cluster_Name', models.TextField()),
                ('go_terms', models.TextField()),
                ('alnfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.AlignmentFile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('aligner', models.CharField(choices=[('bwa', 'BWA'), ('diamond', 'DIAMOND')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alignmenthit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='alignmentfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
