# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignmentfile',
            name='status',
            field=models.TextField(default='new'),
            preserve_default=False,
        ),
    ]
