# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alignmentfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qseqid', models.TextField()),
                ('sseqid', models.TextField()),
                ('pident', models.TextField()),
                ('length', models.TextField()),
                ('mismatch', models.TextField()),
                ('gapopen', models.TextField()),
                ('qstart', models.TextField()),
                ('qend', models.TextField()),
                ('sstart', models.TextField()),
                ('send', models.TextField()),
                ('evalue', models.TextField()),
                ('bitscore', models.TextField()),
                ('GI', models.TextField()),
                ('GeneID', models.TextField()),
                ('NCBI_taxon_of_the_reference', models.TextField()),
                ('Lowest_taxon_of_the_cluster', models.TextField()),
                ('RepID', models.TextField()),
                ('Cluster_Name', models.TextField()),
                ('alnfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.AlignmentFile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
