# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_task_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_taken',
            field=models.TimeField(null=True),
        ),
    ]
